/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConfiguracoesIndexRouteImport } from './routes/_authenticated/configuracoes.index'
import { Route as AuthenticatedVendasVendasRouteImport } from './routes/_authenticated/vendas.vendas'
import { Route as AuthenticatedVendasPedidosRouteImport } from './routes/_authenticated/vendas.pedidos'
import { Route as AuthenticatedVendasCrmRouteImport } from './routes/_authenticated/vendas.crm'
import { Route as AuthenticatedVendasClientesRouteImport } from './routes/_authenticated/vendas.clientes'
import { Route as AuthenticatedRhFolhaRouteImport } from './routes/_authenticated/rh.folha'
import { Route as AuthenticatedRhComissoesRouteImport } from './routes/_authenticated/rh.comissoes'
import { Route as AuthenticatedRhColaboradoresRouteImport } from './routes/_authenticated/rh.colaboradores'
import { Route as AuthenticatedRhAdiantamentosRouteImport } from './routes/_authenticated/rh.adiantamentos'
import { Route as AuthenticatedProjetosProjetosRouteImport } from './routes/_authenticated/projetos.projetos'
import { Route as AuthenticatedProjetosOsRouteImport } from './routes/_authenticated/projetos.os'
import { Route as AuthenticatedFiscalNotasRouteImport } from './routes/_authenticated/fiscal.notas'
import { Route as AuthenticatedFinanceiroTransferenciasRouteImport } from './routes/_authenticated/financeiro.transferencias'
import { Route as AuthenticatedFinanceiroRelatoriosRouteImport } from './routes/_authenticated/financeiro.relatorios'
import { Route as AuthenticatedFinanceiroReceberRouteImport } from './routes/_authenticated/financeiro.receber'
import { Route as AuthenticatedFinanceiroPagarRouteImport } from './routes/_authenticated/financeiro.pagar'
import { Route as AuthenticatedFinanceiroFluxoRouteImport } from './routes/_authenticated/financeiro.fluxo'
import { Route as AuthenticatedFinanceiroExtratoRouteImport } from './routes/_authenticated/financeiro.extrato'
import { Route as AuthenticatedFinanceiroEmprestimosRouteImport } from './routes/_authenticated/financeiro.emprestimos'
import { Route as AuthenticatedFinanceiroDreRouteImport } from './routes/_authenticated/financeiro.dre'
import { Route as AuthenticatedFinanceiroContasRouteImport } from './routes/_authenticated/financeiro.contas'
import { Route as AuthenticatedFinanceiroConciliacaoRouteImport } from './routes/_authenticated/financeiro.conciliacao'
import { Route as AuthenticatedFinanceiroCadastrosRouteImport } from './routes/_authenticated/financeiro.cadastros'
import { Route as AuthenticatedEstoqueProdutosRouteImport } from './routes/_authenticated/estoque.produtos'
import { Route as AuthenticatedEstoqueMovimentacoesRouteImport } from './routes/_authenticated/estoque.movimentacoes'
import { Route as AuthenticatedEstoqueFornecedoresRouteImport } from './routes/_authenticated/estoque.fornecedores'
import { Route as AuthenticatedEstoqueComprasRouteImport } from './routes/_authenticated/estoque.compras'
import { Route as AuthenticatedConfiguracoesEmpresasRouteImport } from './routes/_authenticated/configuracoes.empresas'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesIndexRoute =
  AuthenticatedConfiguracoesIndexRouteImport.update({
    id: '/configuracoes/',
    path: '/configuracoes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendasVendasRoute =
  AuthenticatedVendasVendasRouteImport.update({
    id: '/vendas/vendas',
    path: '/vendas/vendas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendasPedidosRoute =
  AuthenticatedVendasPedidosRouteImport.update({
    id: '/vendas/pedidos',
    path: '/vendas/pedidos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendasCrmRoute = AuthenticatedVendasCrmRouteImport.update({
  id: '/vendas/crm',
  path: '/vendas/crm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVendasClientesRoute =
  AuthenticatedVendasClientesRouteImport.update({
    id: '/vendas/clientes',
    path: '/vendas/clientes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRhFolhaRoute = AuthenticatedRhFolhaRouteImport.update({
  id: '/rh/folha',
  path: '/rh/folha',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRhComissoesRoute =
  AuthenticatedRhComissoesRouteImport.update({
    id: '/rh/comissoes',
    path: '/rh/comissoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRhColaboradoresRoute =
  AuthenticatedRhColaboradoresRouteImport.update({
    id: '/rh/colaboradores',
    path: '/rh/colaboradores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRhAdiantamentosRoute =
  AuthenticatedRhAdiantamentosRouteImport.update({
    id: '/rh/adiantamentos',
    path: '/rh/adiantamentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjetosProjetosRoute =
  AuthenticatedProjetosProjetosRouteImport.update({
    id: '/projetos/projetos',
    path: '/projetos/projetos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjetosOsRoute = AuthenticatedProjetosOsRouteImport.update({
  id: '/projetos/os',
  path: '/projetos/os',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFiscalNotasRoute =
  AuthenticatedFiscalNotasRouteImport.update({
    id: '/fiscal/notas',
    path: '/fiscal/notas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroTransferenciasRoute =
  AuthenticatedFinanceiroTransferenciasRouteImport.update({
    id: '/financeiro/transferencias',
    path: '/financeiro/transferencias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroRelatoriosRoute =
  AuthenticatedFinanceiroRelatoriosRouteImport.update({
    id: '/financeiro/relatorios',
    path: '/financeiro/relatorios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroReceberRoute =
  AuthenticatedFinanceiroReceberRouteImport.update({
    id: '/financeiro/receber',
    path: '/financeiro/receber',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroPagarRoute =
  AuthenticatedFinanceiroPagarRouteImport.update({
    id: '/financeiro/pagar',
    path: '/financeiro/pagar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroFluxoRoute =
  AuthenticatedFinanceiroFluxoRouteImport.update({
    id: '/financeiro/fluxo',
    path: '/financeiro/fluxo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroExtratoRoute =
  AuthenticatedFinanceiroExtratoRouteImport.update({
    id: '/financeiro/extrato',
    path: '/financeiro/extrato',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroEmprestimosRoute =
  AuthenticatedFinanceiroEmprestimosRouteImport.update({
    id: '/financeiro/emprestimos',
    path: '/financeiro/emprestimos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroDreRoute =
  AuthenticatedFinanceiroDreRouteImport.update({
    id: '/financeiro/dre',
    path: '/financeiro/dre',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroContasRoute =
  AuthenticatedFinanceiroContasRouteImport.update({
    id: '/financeiro/contas',
    path: '/financeiro/contas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroConciliacaoRoute =
  AuthenticatedFinanceiroConciliacaoRouteImport.update({
    id: '/financeiro/conciliacao',
    path: '/financeiro/conciliacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroCadastrosRoute =
  AuthenticatedFinanceiroCadastrosRouteImport.update({
    id: '/financeiro/cadastros',
    path: '/financeiro/cadastros',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEstoqueProdutosRoute =
  AuthenticatedEstoqueProdutosRouteImport.update({
    id: '/estoque/produtos',
    path: '/estoque/produtos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEstoqueMovimentacoesRoute =
  AuthenticatedEstoqueMovimentacoesRouteImport.update({
    id: '/estoque/movimentacoes',
    path: '/estoque/movimentacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEstoqueFornecedoresRoute =
  AuthenticatedEstoqueFornecedoresRouteImport.update({
    id: '/estoque/fornecedores',
    path: '/estoque/fornecedores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEstoqueComprasRoute =
  AuthenticatedEstoqueComprasRouteImport.update({
    id: '/estoque/compras',
    path: '/estoque/compras',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfiguracoesEmpresasRoute =
  AuthenticatedConfiguracoesEmpresasRouteImport.update({
    id: '/configuracoes/empresas',
    path: '/configuracoes/empresas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/configuracoes/empresas': typeof AuthenticatedConfiguracoesEmpresasRoute
  '/estoque/compras': typeof AuthenticatedEstoqueComprasRoute
  '/estoque/fornecedores': typeof AuthenticatedEstoqueFornecedoresRoute
  '/estoque/movimentacoes': typeof AuthenticatedEstoqueMovimentacoesRoute
  '/estoque/produtos': typeof AuthenticatedEstoqueProdutosRoute
  '/financeiro/cadastros': typeof AuthenticatedFinanceiroCadastrosRoute
  '/financeiro/conciliacao': typeof AuthenticatedFinanceiroConciliacaoRoute
  '/financeiro/contas': typeof AuthenticatedFinanceiroContasRoute
  '/financeiro/dre': typeof AuthenticatedFinanceiroDreRoute
  '/financeiro/emprestimos': typeof AuthenticatedFinanceiroEmprestimosRoute
  '/financeiro/extrato': typeof AuthenticatedFinanceiroExtratoRoute
  '/financeiro/fluxo': typeof AuthenticatedFinanceiroFluxoRoute
  '/financeiro/pagar': typeof AuthenticatedFinanceiroPagarRoute
  '/financeiro/receber': typeof AuthenticatedFinanceiroReceberRoute
  '/financeiro/relatorios': typeof AuthenticatedFinanceiroRelatoriosRoute
  '/financeiro/transferencias': typeof AuthenticatedFinanceiroTransferenciasRoute
  '/fiscal/notas': typeof AuthenticatedFiscalNotasRoute
  '/projetos/os': typeof AuthenticatedProjetosOsRoute
  '/projetos/projetos': typeof AuthenticatedProjetosProjetosRoute
  '/rh/adiantamentos': typeof AuthenticatedRhAdiantamentosRoute
  '/rh/colaboradores': typeof AuthenticatedRhColaboradoresRoute
  '/rh/comissoes': typeof AuthenticatedRhComissoesRoute
  '/rh/folha': typeof AuthenticatedRhFolhaRoute
  '/vendas/clientes': typeof AuthenticatedVendasClientesRoute
  '/vendas/crm': typeof AuthenticatedVendasCrmRoute
  '/vendas/pedidos': typeof AuthenticatedVendasPedidosRoute
  '/vendas/vendas': typeof AuthenticatedVendasVendasRoute
  '/configuracoes/': typeof AuthenticatedConfiguracoesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/configuracoes/empresas': typeof AuthenticatedConfiguracoesEmpresasRoute
  '/estoque/compras': typeof AuthenticatedEstoqueComprasRoute
  '/estoque/fornecedores': typeof AuthenticatedEstoqueFornecedoresRoute
  '/estoque/movimentacoes': typeof AuthenticatedEstoqueMovimentacoesRoute
  '/estoque/produtos': typeof AuthenticatedEstoqueProdutosRoute
  '/financeiro/cadastros': typeof AuthenticatedFinanceiroCadastrosRoute
  '/financeiro/conciliacao': typeof AuthenticatedFinanceiroConciliacaoRoute
  '/financeiro/contas': typeof AuthenticatedFinanceiroContasRoute
  '/financeiro/dre': typeof AuthenticatedFinanceiroDreRoute
  '/financeiro/emprestimos': typeof AuthenticatedFinanceiroEmprestimosRoute
  '/financeiro/extrato': typeof AuthenticatedFinanceiroExtratoRoute
  '/financeiro/fluxo': typeof AuthenticatedFinanceiroFluxoRoute
  '/financeiro/pagar': typeof AuthenticatedFinanceiroPagarRoute
  '/financeiro/receber': typeof AuthenticatedFinanceiroReceberRoute
  '/financeiro/relatorios': typeof AuthenticatedFinanceiroRelatoriosRoute
  '/financeiro/transferencias': typeof AuthenticatedFinanceiroTransferenciasRoute
  '/fiscal/notas': typeof AuthenticatedFiscalNotasRoute
  '/projetos/os': typeof AuthenticatedProjetosOsRoute
  '/projetos/projetos': typeof AuthenticatedProjetosProjetosRoute
  '/rh/adiantamentos': typeof AuthenticatedRhAdiantamentosRoute
  '/rh/colaboradores': typeof AuthenticatedRhColaboradoresRoute
  '/rh/comissoes': typeof AuthenticatedRhComissoesRoute
  '/rh/folha': typeof AuthenticatedRhFolhaRoute
  '/vendas/clientes': typeof AuthenticatedVendasClientesRoute
  '/vendas/crm': typeof AuthenticatedVendasCrmRoute
  '/vendas/pedidos': typeof AuthenticatedVendasPedidosRoute
  '/vendas/vendas': typeof AuthenticatedVendasVendasRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/configuracoes/empresas': typeof AuthenticatedConfiguracoesEmpresasRoute
  '/_authenticated/estoque/compras': typeof AuthenticatedEstoqueComprasRoute
  '/_authenticated/estoque/fornecedores': typeof AuthenticatedEstoqueFornecedoresRoute
  '/_authenticated/estoque/movimentacoes': typeof AuthenticatedEstoqueMovimentacoesRoute
  '/_authenticated/estoque/produtos': typeof AuthenticatedEstoqueProdutosRoute
  '/_authenticated/financeiro/cadastros': typeof AuthenticatedFinanceiroCadastrosRoute
  '/_authenticated/financeiro/conciliacao': typeof AuthenticatedFinanceiroConciliacaoRoute
  '/_authenticated/financeiro/contas': typeof AuthenticatedFinanceiroContasRoute
  '/_authenticated/financeiro/dre': typeof AuthenticatedFinanceiroDreRoute
  '/_authenticated/financeiro/emprestimos': typeof AuthenticatedFinanceiroEmprestimosRoute
  '/_authenticated/financeiro/extrato': typeof AuthenticatedFinanceiroExtratoRoute
  '/_authenticated/financeiro/fluxo': typeof AuthenticatedFinanceiroFluxoRoute
  '/_authenticated/financeiro/pagar': typeof AuthenticatedFinanceiroPagarRoute
  '/_authenticated/financeiro/receber': typeof AuthenticatedFinanceiroReceberRoute
  '/_authenticated/financeiro/relatorios': typeof AuthenticatedFinanceiroRelatoriosRoute
  '/_authenticated/financeiro/transferencias': typeof AuthenticatedFinanceiroTransferenciasRoute
  '/_authenticated/fiscal/notas': typeof AuthenticatedFiscalNotasRoute
  '/_authenticated/projetos/os': typeof AuthenticatedProjetosOsRoute
  '/_authenticated/projetos/projetos': typeof AuthenticatedProjetosProjetosRoute
  '/_authenticated/rh/adiantamentos': typeof AuthenticatedRhAdiantamentosRoute
  '/_authenticated/rh/colaboradores': typeof AuthenticatedRhColaboradoresRoute
  '/_authenticated/rh/comissoes': typeof AuthenticatedRhComissoesRoute
  '/_authenticated/rh/folha': typeof AuthenticatedRhFolhaRoute
  '/_authenticated/vendas/clientes': typeof AuthenticatedVendasClientesRoute
  '/_authenticated/vendas/crm': typeof AuthenticatedVendasCrmRoute
  '/_authenticated/vendas/pedidos': typeof AuthenticatedVendasPedidosRoute
  '/_authenticated/vendas/vendas': typeof AuthenticatedVendasVendasRoute
  '/_authenticated/configuracoes/': typeof AuthenticatedConfiguracoesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/dashboard'
    | '/configuracoes/empresas'
    | '/estoque/compras'
    | '/estoque/fornecedores'
    | '/estoque/movimentacoes'
    | '/estoque/produtos'
    | '/financeiro/cadastros'
    | '/financeiro/conciliacao'
    | '/financeiro/contas'
    | '/financeiro/dre'
    | '/financeiro/emprestimos'
    | '/financeiro/extrato'
    | '/financeiro/fluxo'
    | '/financeiro/pagar'
    | '/financeiro/receber'
    | '/financeiro/relatorios'
    | '/financeiro/transferencias'
    | '/fiscal/notas'
    | '/projetos/os'
    | '/projetos/projetos'
    | '/rh/adiantamentos'
    | '/rh/colaboradores'
    | '/rh/comissoes'
    | '/rh/folha'
    | '/vendas/clientes'
    | '/vendas/crm'
    | '/vendas/pedidos'
    | '/vendas/vendas'
    | '/configuracoes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/dashboard'
    | '/configuracoes/empresas'
    | '/estoque/compras'
    | '/estoque/fornecedores'
    | '/estoque/movimentacoes'
    | '/estoque/produtos'
    | '/financeiro/cadastros'
    | '/financeiro/conciliacao'
    | '/financeiro/contas'
    | '/financeiro/dre'
    | '/financeiro/emprestimos'
    | '/financeiro/extrato'
    | '/financeiro/fluxo'
    | '/financeiro/pagar'
    | '/financeiro/receber'
    | '/financeiro/relatorios'
    | '/financeiro/transferencias'
    | '/fiscal/notas'
    | '/projetos/os'
    | '/projetos/projetos'
    | '/rh/adiantamentos'
    | '/rh/colaboradores'
    | '/rh/comissoes'
    | '/rh/folha'
    | '/vendas/clientes'
    | '/vendas/crm'
    | '/vendas/pedidos'
    | '/vendas/vendas'
    | '/configuracoes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/dashboard'
    | '/_authenticated/configuracoes/empresas'
    | '/_authenticated/estoque/compras'
    | '/_authenticated/estoque/fornecedores'
    | '/_authenticated/estoque/movimentacoes'
    | '/_authenticated/estoque/produtos'
    | '/_authenticated/financeiro/cadastros'
    | '/_authenticated/financeiro/conciliacao'
    | '/_authenticated/financeiro/contas'
    | '/_authenticated/financeiro/dre'
    | '/_authenticated/financeiro/emprestimos'
    | '/_authenticated/financeiro/extrato'
    | '/_authenticated/financeiro/fluxo'
    | '/_authenticated/financeiro/pagar'
    | '/_authenticated/financeiro/receber'
    | '/_authenticated/financeiro/relatorios'
    | '/_authenticated/financeiro/transferencias'
    | '/_authenticated/fiscal/notas'
    | '/_authenticated/projetos/os'
    | '/_authenticated/projetos/projetos'
    | '/_authenticated/rh/adiantamentos'
    | '/_authenticated/rh/colaboradores'
    | '/_authenticated/rh/comissoes'
    | '/_authenticated/rh/folha'
    | '/_authenticated/vendas/clientes'
    | '/_authenticated/vendas/crm'
    | '/_authenticated/vendas/pedidos'
    | '/_authenticated/vendas/vendas'
    | '/_authenticated/configuracoes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes/': {
      id: '/_authenticated/configuracoes/'
      path: '/configuracoes'
      fullPath: '/configuracoes/'
      preLoaderRoute: typeof AuthenticatedConfiguracoesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendas/vendas': {
      id: '/_authenticated/vendas/vendas'
      path: '/vendas/vendas'
      fullPath: '/vendas/vendas'
      preLoaderRoute: typeof AuthenticatedVendasVendasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendas/pedidos': {
      id: '/_authenticated/vendas/pedidos'
      path: '/vendas/pedidos'
      fullPath: '/vendas/pedidos'
      preLoaderRoute: typeof AuthenticatedVendasPedidosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendas/crm': {
      id: '/_authenticated/vendas/crm'
      path: '/vendas/crm'
      fullPath: '/vendas/crm'
      preLoaderRoute: typeof AuthenticatedVendasCrmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendas/clientes': {
      id: '/_authenticated/vendas/clientes'
      path: '/vendas/clientes'
      fullPath: '/vendas/clientes'
      preLoaderRoute: typeof AuthenticatedVendasClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rh/folha': {
      id: '/_authenticated/rh/folha'
      path: '/rh/folha'
      fullPath: '/rh/folha'
      preLoaderRoute: typeof AuthenticatedRhFolhaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rh/comissoes': {
      id: '/_authenticated/rh/comissoes'
      path: '/rh/comissoes'
      fullPath: '/rh/comissoes'
      preLoaderRoute: typeof AuthenticatedRhComissoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rh/colaboradores': {
      id: '/_authenticated/rh/colaboradores'
      path: '/rh/colaboradores'
      fullPath: '/rh/colaboradores'
      preLoaderRoute: typeof AuthenticatedRhColaboradoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rh/adiantamentos': {
      id: '/_authenticated/rh/adiantamentos'
      path: '/rh/adiantamentos'
      fullPath: '/rh/adiantamentos'
      preLoaderRoute: typeof AuthenticatedRhAdiantamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projetos/projetos': {
      id: '/_authenticated/projetos/projetos'
      path: '/projetos/projetos'
      fullPath: '/projetos/projetos'
      preLoaderRoute: typeof AuthenticatedProjetosProjetosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projetos/os': {
      id: '/_authenticated/projetos/os'
      path: '/projetos/os'
      fullPath: '/projetos/os'
      preLoaderRoute: typeof AuthenticatedProjetosOsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fiscal/notas': {
      id: '/_authenticated/fiscal/notas'
      path: '/fiscal/notas'
      fullPath: '/fiscal/notas'
      preLoaderRoute: typeof AuthenticatedFiscalNotasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro/transferencias': {
      id: '/_authenticated/financeiro/transferencias'
      path: '/financeiro/transferencias'
      fullPath: '/financeiro/transferencias'
      preLoaderRoute: typeof AuthenticatedFinanceiroTransferenciasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro/relatorios': {
      id: '/_authenticated/financeiro/relatorios'
      path: '/financeiro/relatorios'
      fullPath: '/financeiro/relatorios'
      preLoaderRoute: typeof AuthenticatedFinanceiroRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro/receber': {
      id: '/_authenticated/financeiro/receber'
      path: '/financeiro/receber'
      fullPath: '/financeiro/receber'
      preLoaderRoute: typeof AuthenticatedFinanceiroReceberRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro/pagar': {
      id: '/_authenticated/financeiro/pagar'
      path: '/financeiro/pagar'
      fullPath: '/financeiro/pagar'
      preLoaderRoute: typeof AuthenticatedFinanceiroPagarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro/fluxo': {
      id: '/_authenticated/financeiro/fluxo'
      path: '/financeiro/fluxo'
      fullPath: '/financeiro/fluxo'
      preLoaderRoute: typeof AuthenticatedFinanceiroFluxoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro/extrato': {
      id: '/_authenticated/financeiro/extrato'
      path: '/financeiro/extrato'
      fullPath: '/financeiro/extrato'
      preLoaderRoute: typeof AuthenticatedFinanceiroExtratoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro/emprestimos': {
      id: '/_authenticated/financeiro/emprestimos'
      path: '/financeiro/emprestimos'
      fullPath: '/financeiro/emprestimos'
      preLoaderRoute: typeof AuthenticatedFinanceiroEmprestimosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro/dre': {
      id: '/_authenticated/financeiro/dre'
      path: '/financeiro/dre'
      fullPath: '/financeiro/dre'
      preLoaderRoute: typeof AuthenticatedFinanceiroDreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro/contas': {
      id: '/_authenticated/financeiro/contas'
      path: '/financeiro/contas'
      fullPath: '/financeiro/contas'
      preLoaderRoute: typeof AuthenticatedFinanceiroContasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro/conciliacao': {
      id: '/_authenticated/financeiro/conciliacao'
      path: '/financeiro/conciliacao'
      fullPath: '/financeiro/conciliacao'
      preLoaderRoute: typeof AuthenticatedFinanceiroConciliacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro/cadastros': {
      id: '/_authenticated/financeiro/cadastros'
      path: '/financeiro/cadastros'
      fullPath: '/financeiro/cadastros'
      preLoaderRoute: typeof AuthenticatedFinanceiroCadastrosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estoque/produtos': {
      id: '/_authenticated/estoque/produtos'
      path: '/estoque/produtos'
      fullPath: '/estoque/produtos'
      preLoaderRoute: typeof AuthenticatedEstoqueProdutosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estoque/movimentacoes': {
      id: '/_authenticated/estoque/movimentacoes'
      path: '/estoque/movimentacoes'
      fullPath: '/estoque/movimentacoes'
      preLoaderRoute: typeof AuthenticatedEstoqueMovimentacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estoque/fornecedores': {
      id: '/_authenticated/estoque/fornecedores'
      path: '/estoque/fornecedores'
      fullPath: '/estoque/fornecedores'
      preLoaderRoute: typeof AuthenticatedEstoqueFornecedoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estoque/compras': {
      id: '/_authenticated/estoque/compras'
      path: '/estoque/compras'
      fullPath: '/estoque/compras'
      preLoaderRoute: typeof AuthenticatedEstoqueComprasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes/empresas': {
      id: '/_authenticated/configuracoes/empresas'
      path: '/configuracoes/empresas'
      fullPath: '/configuracoes/empresas'
      preLoaderRoute: typeof AuthenticatedConfiguracoesEmpresasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedConfiguracoesEmpresasRoute: typeof AuthenticatedConfiguracoesEmpresasRoute
  AuthenticatedEstoqueComprasRoute: typeof AuthenticatedEstoqueComprasRoute
  AuthenticatedEstoqueFornecedoresRoute: typeof AuthenticatedEstoqueFornecedoresRoute
  AuthenticatedEstoqueMovimentacoesRoute: typeof AuthenticatedEstoqueMovimentacoesRoute
  AuthenticatedEstoqueProdutosRoute: typeof AuthenticatedEstoqueProdutosRoute
  AuthenticatedFinanceiroCadastrosRoute: typeof AuthenticatedFinanceiroCadastrosRoute
  AuthenticatedFinanceiroConciliacaoRoute: typeof AuthenticatedFinanceiroConciliacaoRoute
  AuthenticatedFinanceiroContasRoute: typeof AuthenticatedFinanceiroContasRoute
  AuthenticatedFinanceiroDreRoute: typeof AuthenticatedFinanceiroDreRoute
  AuthenticatedFinanceiroEmprestimosRoute: typeof AuthenticatedFinanceiroEmprestimosRoute
  AuthenticatedFinanceiroExtratoRoute: typeof AuthenticatedFinanceiroExtratoRoute
  AuthenticatedFinanceiroFluxoRoute: typeof AuthenticatedFinanceiroFluxoRoute
  AuthenticatedFinanceiroPagarRoute: typeof AuthenticatedFinanceiroPagarRoute
  AuthenticatedFinanceiroReceberRoute: typeof AuthenticatedFinanceiroReceberRoute
  AuthenticatedFinanceiroRelatoriosRoute: typeof AuthenticatedFinanceiroRelatoriosRoute
  AuthenticatedFinanceiroTransferenciasRoute: typeof AuthenticatedFinanceiroTransferenciasRoute
  AuthenticatedFiscalNotasRoute: typeof AuthenticatedFiscalNotasRoute
  AuthenticatedProjetosOsRoute: typeof AuthenticatedProjetosOsRoute
  AuthenticatedProjetosProjetosRoute: typeof AuthenticatedProjetosProjetosRoute
  AuthenticatedRhAdiantamentosRoute: typeof AuthenticatedRhAdiantamentosRoute
  AuthenticatedRhColaboradoresRoute: typeof AuthenticatedRhColaboradoresRoute
  AuthenticatedRhComissoesRoute: typeof AuthenticatedRhComissoesRoute
  AuthenticatedRhFolhaRoute: typeof AuthenticatedRhFolhaRoute
  AuthenticatedVendasClientesRoute: typeof AuthenticatedVendasClientesRoute
  AuthenticatedVendasCrmRoute: typeof AuthenticatedVendasCrmRoute
  AuthenticatedVendasPedidosRoute: typeof AuthenticatedVendasPedidosRoute
  AuthenticatedVendasVendasRoute: typeof AuthenticatedVendasVendasRoute
  AuthenticatedConfiguracoesIndexRoute: typeof AuthenticatedConfiguracoesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedConfiguracoesEmpresasRoute:
    AuthenticatedConfiguracoesEmpresasRoute,
  AuthenticatedEstoqueComprasRoute: AuthenticatedEstoqueComprasRoute,
  AuthenticatedEstoqueFornecedoresRoute: AuthenticatedEstoqueFornecedoresRoute,
  AuthenticatedEstoqueMovimentacoesRoute:
    AuthenticatedEstoqueMovimentacoesRoute,
  AuthenticatedEstoqueProdutosRoute: AuthenticatedEstoqueProdutosRoute,
  AuthenticatedFinanceiroCadastrosRoute: AuthenticatedFinanceiroCadastrosRoute,
  AuthenticatedFinanceiroConciliacaoRoute:
    AuthenticatedFinanceiroConciliacaoRoute,
  AuthenticatedFinanceiroContasRoute: AuthenticatedFinanceiroContasRoute,
  AuthenticatedFinanceiroDreRoute: AuthenticatedFinanceiroDreRoute,
  AuthenticatedFinanceiroEmprestimosRoute:
    AuthenticatedFinanceiroEmprestimosRoute,
  AuthenticatedFinanceiroExtratoRoute: AuthenticatedFinanceiroExtratoRoute,
  AuthenticatedFinanceiroFluxoRoute: AuthenticatedFinanceiroFluxoRoute,
  AuthenticatedFinanceiroPagarRoute: AuthenticatedFinanceiroPagarRoute,
  AuthenticatedFinanceiroReceberRoute: AuthenticatedFinanceiroReceberRoute,
  AuthenticatedFinanceiroRelatoriosRoute:
    AuthenticatedFinanceiroRelatoriosRoute,
  AuthenticatedFinanceiroTransferenciasRoute:
    AuthenticatedFinanceiroTransferenciasRoute,
  AuthenticatedFiscalNotasRoute: AuthenticatedFiscalNotasRoute,
  AuthenticatedProjetosOsRoute: AuthenticatedProjetosOsRoute,
  AuthenticatedProjetosProjetosRoute: AuthenticatedProjetosProjetosRoute,
  AuthenticatedRhAdiantamentosRoute: AuthenticatedRhAdiantamentosRoute,
  AuthenticatedRhColaboradoresRoute: AuthenticatedRhColaboradoresRoute,
  AuthenticatedRhComissoesRoute: AuthenticatedRhComissoesRoute,
  AuthenticatedRhFolhaRoute: AuthenticatedRhFolhaRoute,
  AuthenticatedVendasClientesRoute: AuthenticatedVendasClientesRoute,
  AuthenticatedVendasCrmRoute: AuthenticatedVendasCrmRoute,
  AuthenticatedVendasPedidosRoute: AuthenticatedVendasPedidosRoute,
  AuthenticatedVendasVendasRoute: AuthenticatedVendasVendasRoute,
  AuthenticatedConfiguracoesIndexRoute: AuthenticatedConfiguracoesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
